# Generated by Django 2.0.4 on 2018-04-29 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genre',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='genre',
            name='last_name',
        ),
    ]
