# Generated by Django 2.0.4 on 2018-04-30 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0004_auto_20180430_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='biography',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='actor',
            name='birth_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='actor',
            name='profile_path',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='director',
            name='biography',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='director',
            name='birth_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='director',
            name='gender',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='director',
            name='profile_path',
            field=models.TextField(null=True),
        ),
    ]
